Repository adobe/adobe-design-website, pull requests merged in 2025-05, with the labels that each got.

#64 fix: footer horizontal scroll
  blocks/footer-copyright/footer-copyright.css
  blocks/footer/footer.css
Labels: Ready for Dev Review

#69 feat: callout block
  blocks/callout/callout.css
  blocks/callout/callout.js
  blocks/callout/callout.test.js
  styles/base.css
  styles/styles.css
Labels: Ready for Rebase & Merge

#66 feat: two-up layout
  blocks/cards/cards.test.js
  blocks/link-list/link-list.js
  blocks/link-list/link-list.test.js
  scripts/aem.js
  scripts/scripts.js
  styles/styles.css
Labels: Ready for Dev Review

#75 fix: replace reference to undefined rgb tokens
  styles/base.css
Labels: Ready for Dev Review

#73 feat: job listing and job list
  blocks/job-list/job-list.css
  blocks/job-list/job-list.js
  blocks/job-list/job-list.test.js
  blocks/job-listing/job-listing.css
  blocks/job-listing/job-listing.js
  blocks/job-listing/job-listing.test.js
Labels: Ready for Dev Review

#68 feat: nav toolbar
  blocks/filter-group/filter-group.css
  blocks/footer/footer.css
  blocks/header/header.css
  blocks/header/header.js
  blocks/header/nav-toolbar.js
  blocks/search/search.css
  blocks/search/search.js
  blocks/search/search.test.js
  head.html
  scripts/scripts.js
  styles/base.css
  styles/styles.css
Labels: Ready for Dev Review, Ready for Rebase & Merge

#71 feat: section header
  blocks-helpers/cleanText.js
  blocks/button-group/button-group.css
  blocks/button-group/button-group.js
  blocks/callout/callout.js
  blocks/section-header/section-header.css
  blocks/section-header/section-header.js
  blocks/section-header/section-header.test.js
  styles/styles.css
Labels: Ready for Dev Review

#74 feat: add lede block
  blocks/lede/lede.css
  blocks/lede/lede.js
  blocks/lede/lede.test.js
  blocks/quote/quote.css
  blocks/quote/quote.js
  styles/styles.css
Labels: Ready for Dev Review

#72 feat: article-header
  blocks-helpers/prepURL.js
  blocks-helpers/skipLinks.js
  blocks/article-header/article-header.css
  blocks/article-header/article-header.js
  blocks/article-header/article-header.test.js
  blocks/modal/modal.test.js
  styles/styles.css
Labels: Ready for Dev Review

#63 feat: add card block and styles
  blocks/card/card.css
  blocks/card/card.js
  blocks/card/card.test.js
  blocks/cards/cards.css
  blocks/cards/cards.js
  blocks/cards/cards.test.js
  styles/base.css
Labels: Ready for Dev Review

#78 feat: page header
  blocks/page-header/page-header.css
  blocks/page-header/page-header.js
  blocks/page-header/page-header.test.js
  styles/styles.css
Labels: Ready for Dev Review

#80 feat: additional layouts
  blocks/card/card.css
  blocks/card/card.js
  scripts/aem.js
  styles/base.css
  styles/styles.css
Labels: Ready for Rebase & Merge

#85 feat: image and image-with-caption
  blocks/footer/footer.test.js
  blocks/image-with-caption/image-with-caption.css
  blocks/image-with-caption/image-with-caption.js
  blocks/image-with-caption/image-with-caption.test.js
  scripts/scripts.js
  styles/styles.css
Labels: Ready for Rebase & Merge

#84 feat: small screen CTA
  blocks/card/card.css
  blocks/footer/footer.css
  blocks/small-screen-cta/small-screen-cta.css
  blocks/small-screen-cta/small-screen-cta.js
  blocks/small-screen-cta/small-screen-cta.test.js
  styles/base.css
  styles/styles.css
Labels: Ready for Dev Review

#88 feat: gradients and theme change, and rounded diamond themes
  assets/themes/shapes.js
  blocks/header/header.js
  scripts/aem.js
  scripts/modules/themeBackgrounds.js
  scripts/scripts.js
  styles/base.css
  styles/styles.css
Labels: Ready for Squash & Merge

#91 feat: add additional gradient themes
  assets/themes/shapes.js
  blocks/hero/hero.test.js
  scripts/modules/themeBackgrounds.js
  styles/base.css
  styles/styles.css
Labels: Ready for Squash & Merge
