Repository adobe/adobe-design-website, pull requests merged in 2025-06, with the labels that each got.

#98 feat: career page adjustments
  blocks/callout/callout.css
  blocks/callout/callout.js
  blocks/job-list/job-list.js
  blocks/job-listing/job-listing.css
  styles/base.css
  styles/global-blocks.css
Labels: Ready for Dev Review

#101 feat: feature layout block
  blocks/feature-layout/feature-layout.css
  blocks/feature-layout/feature-layout.js
  blocks/feature-layout/feature-layout.test.js
Labels: Changes Requested

#105 feat: add all properties to helix-query config
  helix-query.yaml
Labels: Ready for Squash & Merge

#103 feat: recent ideas block
  blocks/callout/callout.js
  blocks/card/card.js
  blocks/recent-ideas/recent-ideas.css
  blocks/recent-ideas/recent-ideas.js
  blocks/recent-ideas/recent-ideas.test.js
  scripts/dataStore.js
  scripts/helpers/appendCleanText.js
  scripts/helpers/cleanText.js
  scripts/helpers/index.js
  styles/global-blocks.css
Labels: Ready for Squash & Merge

#111 fix: link-list behavior
  blocks/link-list/link-list.css
  blocks/link-list/link-list.js
Labels: Ready for Squash & Merge

#106 feat: article page auto-blocking
  blocks/article-header/article-header.css
  blocks/feature-layout/feature-layout.css
  scripts/aem.js
  scripts/helpers/buildArticlePage.js
  scripts/helpers/buildAuthorAside.js
  scripts/helpers/buildCareersListingPage.js
  scripts/helpers/getAuthorData.js
  scripts/helpers/index.js
  scripts/helpers/loadArticlePreFooter.js
  scripts/scripts.js
  styles/global-blocks.css
  styles/styles.css
Labels: Ready for Squash & Merge

#112 feat: breakpoint and spacing adjustments
  blocks/article-header/article-header.css
  blocks/button-group/button-group.css
  blocks/callout/callout.css
  blocks/feature-layout/feature-layout.css
  blocks/feature-layout/feature-layout.js
  blocks/job-list/job-list.css
  blocks/link-list/link-list.css
  blocks/link-list/link-list.js
  blocks/page-header/page-header.css
  blocks/recent-ideas/recent-ideas.js
  blocks/recent-ideas/recent-ideas.test.js
  blocks/section-header/section-header.css
  blocks/section-header/section-header.js
  blocks/small-screen-cta/small-screen-cta.css
  styles/global-blocks.css
  styles/styles.css
Labels: Ready for Dev Review

#117 feat: add remaining backdrops
  assets/themes/shapes.js
  scripts/aem.js
  scripts/helpers/index.js
  scripts/helpers/themeBackgrounds.js
  scripts/scripts.js
  styles/styles.css
Labels: Ready for Dev Review

#119 fix: bugs from various pages
  blocks/article-header/article-header.css
  blocks/article-header/article-header.js
  blocks/feature-layout/feature-layout.css
  blocks/job-list/job-list.css
  package-lock.json
  styles/global-blocks.css
Labels: Ready for Dev Review

#115 feat: add ideas block and connected functionality
  blocks/filter-group/filter-group-functions.js
  blocks/filter-group/filter-group-temp-mockup.js
  blocks/filter-group/filter-group-utils.js
  blocks/filter-group/filter-group.css
  blocks/filter-group/filter-group.js
  blocks/ideas/ideas-functions.js
  blocks/ideas/ideas.css
  blocks/ideas/ideas.js
  blocks/ideas/ideas.test.js
  blocks/recent-ideas/recent-ideas.js
  scripts/helpers/appendLiveRegion.js
  scripts/helpers/dataStore.js
  scripts/helpers/debounce.js
  scripts/helpers/fetchAndBuildIdeas.js
  scripts/helpers/getCurrentBreakpoint.js
  scripts/helpers/index.js
  scripts/scripts.js
Labels: Ready for Squash & Merge

#123 fix: increase button inline padding
  styles/styles.css
Labels: Ready for Squash & Merge

#130 feat: remove fetch requests for empty css files
  blocks/button-group/button-group.css
  blocks/card/card.css
  blocks/constrained-text/constrained-text.css
  blocks/fragment/fragment.css
  blocks/image-with-caption/image-with-caption.css
  blocks/job-listing/job-listing.css
  blocks/lede/lede.css
  blocks/recent-ideas/recent-ideas.css
  blocks/search/search.css
  scripts/aem.js
  scripts/helpers/blockSettings.js
  scripts/helpers/index.js
Labels: Ready for Squash & Merge

#132 feat: expand browser support for most colors
  blocks/filter-group/filter-group.css
  styles/base.css
  styles/styles.css
Labels: Ready for Dev Review

#133 feat: support multiple article tags
  blocks/article-header/article-header.js
  blocks/filter-group/filter-group-functions.js
  blocks/ideas/ideas-functions.js
  blocks/ideas/ideas.js
  blocks/recent-ideas/recent-ideas.js
  scripts/helpers/buildArticlePage.js
  scripts/helpers/fetchAndBuildIdeas.js
  styles/global-blocks.css
  styles/styles.css
Labels: Ready for Squash & Merge
